services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop-app-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      AZURE_POSTGRES_USER: ${AZURE_POSTGRES_USER}
      AZURE_POSTGRES_PASSWORD: ${AZURE_POSTGRES_PASSWORD}
      AZURE_POSTGRES_DB: ${AZURE_POSTGRES_DB}
      AZURE_POSTGRES_HOST: ${AZURE_POSTGRES_HOST}
      AZURE_POSTGRES_PORT: 5432
      DB_CONNECTION_TYPE: azure
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - app_network

networks:
  app_network:
