name: CI/CD Deployment

on:
  push:
    branches:
      - main
      - master

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_OWNER_SP_APP_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_OWNER_SP_PASSWORD }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  CONTEXT_ACCESS_TOKEN: ${{ secrets.CONTEXT_ACCESS_TOKEN }}
  TF_VAR_context_access_token: ${{ secrets.CONTEXT_ACCESS_TOKEN }}
  TF_VAR_developer_object_id: ${{ secrets.AZURE_DEVELOPER_SP_OBJECT_ID }}
  TF_VAR_owner_object_id: ${{ secrets.AZURE_OWNER_SP_OBJECT_ID }}


jobs:
  terraform:
    name: "Azure SP Login Test"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TERRAFORM_DEPLOY }} 

    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_OWNER_SP_APP_ID }}
        client-secret: ${{ secrets.AZURE_OWNER_SP_PASSWORD }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Verify Azure Account
      run: |
        az account show
