name: Deploy Infrastructure

on:
  push:
    branches:
      - main

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.5

    - name: Configure Azure
      run: |
        az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID

    - name: Initialize Terraform
      run: |
        cd infrastructure
        terraform fmt -recursive
        terraform init

    - name: Validate Terraform
      run: |
        cd infrastructure
        terraform validate

    - name: Plan Infrastructure
      run: |
        cd infrastructure
        terraform plan -out=tfplan

    - name: Apply Infrastructure
      run: |
        cd infrastructure
        terraform apply -auto-approve tfplan
